FROM islasgeci/clean_camera_data:latest
RUN curl -fsSL https://opencode.ai/install | bash
RUN git clone https://github.com/mvillasante/opencode_agents.git /tmp/opencode_agents && \
	cp -r /tmp/opencode_agents/* /root/.opencode/ && \
	rm -rf /tmp/opencode_agents
