services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/seabird_tracking:latest
    command: bash
    volumes:
      - $PWD:/workdir
  develop:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: islasgeci/clean_camera_data_develop:latest
    command: bash
    volumes:
      - $PWD:/workdir
